### ISSUE TITLE
/db/env.sh file availability

### ISSUE THREAD

**Issue by satya66655** [carlosdoki/MovieZtream#1]
Hello Team,.

I was going through this application and following the steps, as per the step 4, I am not finding the env.sh file under db is not available; the folder db itself is not available.

Kindly suggest.

4. Edit the files /mz/env.sh and /db/env.sh with the address of AppDynamics Controller and ports.

**Comment by adrian-gl** [comment]
hey @satya66655 did u fix this ?
Are u able to set the environment up ?

**Comment by satya66655** [comment]
Hello Adrian,.

No, So far not able to fix it.
If you could help me then it would be greatly appreciated.

**Comment by carlosdoki** [comment]
Now it's works.
