### ISSUE TITLE
MovieZtream

### ISSUE THREAD

**Issue by khalidrehan** [carlosdoki/MovieZtream#5]
Starting Exercise4Load...java.io.IOException: Cannot run program "/appdynamics/jmeter/bin/jmeter.sh": error=2, No such file or directory

**Comment by carlosdoki** [comment]
this message when this appears? On start_mz or into the site MovieZtream?

**Comment by khalidrehan** [comment]
Starting SuperBowlLoad...java.io.IOException: Cannot run program "/appdynamics/jmeter/bin/jmeter.sh": error=2, No such file or directory
Starting Errors...
Starting DeadLocks...
Starting Exercise4Load...java.io.IOException: Cannot run program "/appdynamics/jmeter/bin/jmeter.sh": error=2, No such file or directory

**Comment by khalidrehan** [comment]
> this message when this appears? On start_mz or into the site MovieZtream?

I will try to send you all what I see

**Comment by khalidrehan** [comment]
This is a rebuild::
**********************************************************************************


root@movieztream:/home/krehan/Downloads/MovieZtream-master# ./build-mz.sh 
An AppDynamics Portal login is required to download the installer software
Email ID/UserName: 
khalid.rehan@mvsrvs.com
Password: 

Controller Address: 
https://cat2020033104545512.saas.appdynamics.com/
Controller Port (8090/443/8181): 
443
Controller SSL (true/false): 
true
Controller KEY: 
6oxlbabfvi2b

Building MovieZtream container (appdynamics/edu-movieztream)



Building MovieZtream container (appdynamics/edu-movieztream)

cp: cannot stat 'user.dat': No such file or directory
Sending build context to Docker daemon  78.69MB
Step 1/28 : FROM alpine:latest
 ---> a187dde48cd2
Step 2/28 : MAINTAINER Carlos Doki (carlosdoki@gmail.com)
 ---> Using cache
 ---> dcafb8e7e44c
Step 3/28 : RUN apk update && apk add unzip openjdk8 iproute2 curl jq
 ---> Using cache
 ---> 10a956fe7c02
Step 4/28 : RUN mkdir -p /run/lock && mkdir -p /tomcat
 ---> Using cache
 ---> 5549ca535d5d
Step 5/28 : ADD user.dat /
ADD failed: stat /var/lib/docker/tmp/docker-builder773987815/user.dat: no such file or directory

Building db-agent container (appdynamics/edu-db-agent)

cp: cannot stat 'user.dat': No such file or directory
Sending build context to Docker daemon  5.632kB
Step 1/12 : FROM alpine:latest
 ---> a187dde48cd2
Step 2/12 : MAINTAINER Carlos Doki (carlosdoki@gmail.com)
 ---> Using cache
 ---> dcafb8e7e44c
Step 3/12 : RUN apk update && apk add unzip openjdk8 iproute2 curl jq
 ---> Using cache
 ---> 10a956fe7c02
Step 4/12 : RUN mkdir -p /run/lock
 ---> Using cache
 ---> b6504f82f2c7
Step 5/12 : ADD user.dat /
ADD failed: stat /var/lib/docker/tmp/docker-builder065592858/user.dat: no such file or directory

Building JMeter load container (appdynamics/edu-jmeter)

Sending build context to Docker daemon  78.71MB
Step 1/14 : FROM alpine:latest
 ---> a187dde48cd2
Step 2/14 : MAINTAINER Carlos Doki (carlosdoki@gmail.com)
 ---> Using cache
 ---> dcafb8e7e44c
Step 3/14 : RUN apk update && apk add openjdk8
 ---> Using cache
 ---> 77c8d07c0422
Step 4/14 : RUN mkdir -p /run/lock
 ---> Using cache
 ---> 766b13609540
Step 5/14 : RUN mkdir -p /appdynamics
 ---> Using cache
 ---> d71345ef1e64
Step 6/14 : RUN addgroup appdynamics
 ---> Using cache
 ---> d6338b0864fa
Step 7/14 : RUN adduser -D --ingroup appdynamics appdynamics
 ---> Using cache
 ---> f60b7870d937
Step 8/14 : RUN mkdir -p /appdynamics/jmeter
 ---> Using cache
 ---> fe3fdc08a8b0
Step 9/14 : RUN mkdir -p /appdynamics/jmeter/scripts
 ---> Using cache
 ---> 2cefbe955290
Step 10/14 : ADD /jmeter/ /appdynamics/jmeter/
 ---> Using cache
 ---> a96e0bdc9706
Step 11/14 : ADD /scripts/ /appdynamics/jmeter/scripts/
 ---> Using cache
 ---> c411e8a727ca
Step 12/14 : ADD /start.sh /appdynamics/
 ---> Using cache
 ---> e2a46dc1f741
Step 13/14 : RUN chmod a+x /appdynamics/start.sh
 ---> Using cache
 ---> 8b26e5e4f9c0
Step 14/14 : CMD /appdynamics/start.sh && tail -F /appdynamics/jmeter/scripts/jmeter.log
 ---> Using cache
 ---> 057648e05bca
Successfully built 057648e05bca
Successfully tagged carlosdoki/edu-jmeter:latest
Starting the MovieZtream database on container: db...
docker: Error response from daemon: Conflict. The container name "/db" is already in use by container "de34d6ba58805cd0828959591b45b2c399069fe793a690b0b8033ad6bfc1af15". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Error response from daemon: Container de34d6ba58805cd0828959591b45b2c399069fe793a690b0b8033ad6bfc1af15 is not running
Error response from daemon: Container de34d6ba58805cd0828959591b45b2c399069fe793a690b0b8033ad6bfc1af15 is not running
Starting the db-agent on contaioner: db-agent...
docker: Error response from daemon: Conflict. The container name "/db-agent" is already in use by container "4c8b599205aabac8b290a1061a956968be63d51164f213c04a25975cfc90b53c". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Starting MovieZtream application containers: rt, sv, ui...
docker: Error response from daemon: Conflict. The container name "/rt" is already in use by container "f9eb5b4f79f1be8267d79b9a3fc189f34b33f514e9596de46d124fc741785b3f". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
docker: Error response from daemon: Conflict. The container name "/sv" is already in use by container "bf395044b84c2f18118ddbb1b7f4985add327b875067869b5f5e4cafa938ac1e". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
docker: Error response from daemon: Conflict. The container name "/ui" is already in use by container "1cee7f82bb337e74f9fd4fc9224f17398a86b453b6e6ca738203cc2364fb9054". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
Starting the JMeter load container: mz-load...
docker: Error response from daemon: Conflict. The container name "/mz-load" is already in use by container "92086f693df485be4c5c0c7fe79579452731ff7acb7cbf392f2f84df57b24e00". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

All containers started!

root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# 
root@movieztream:/home/krehan/Downloads/MovieZtream-master# ./start-mz.sh 

Starting the MySQL database container...

db

Starting the AppDynamics db agent container...

db-agent

Starting the MovieZtream ratings container...

rt

Starting the MovieZtream service container...

sv

Starting the MovieZtream UI container...

ui

Starting the JMeter load container...

mz-load

Waiting for agent registration...


Starting AppDynamics machine agents on MovieZtream containers...

OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

All containers started! You can access the AppDynamics Controller at :8090

root@movieztream:/home/krehan/Downloads/MovieZtream-master#

**Comment by khalidrehan** [comment]
> this message when this appears? On start_mz or into the site MovieZtream?

Inside the site MovieZtream
![image](https://user-images.githubusercontent.com/37035465/78061449-f1aa1b80-7395-11ea-943e-fb760f42b64b.png)

**Comment by khalidrehan** [comment]
There are some errors while building_MZ, like:
-----------------------------------------------------------------------------------

Building MovieZtream container (appdynamics/edu-movieztream)

cp: cannot stat 'user.dat': No such file or directory

Step 5/28 : ADD user.dat /
ADD failed: stat /var/lib/docker/tmp/docker-builder773987815/user.dat: no such file or directory


Step 5/12 : ADD user.dat /
ADD failed: stat /var/lib/docker/tmp/docker-builder065592858/user.dat: no such file or directory

**Comment by carlosdoki** [comment]
I committed new version.
Run 
`./remove.sh` 
and 
`docker rmi -f $(docker images -a -q)`

After this re-run `./build.sh`

**Comment by khalidrehan** [comment]
Thanks!
One last question, do I need to install my version of Appdynamics Controller? or it is being done via build_mz.sh ?

**Comment by carlosdoki** [comment]
Hi khalidrehan, you need install AppDynamics Controller first.

**Comment by khalidrehan** [comment]
Does it work if the Controller is on SaaS?
I'm trying but it fails.
