### ISSUE TITLE
Errors on root@localhost and on start-mz.sh

### ISSUE THREAD

**Issue by khalidrehan** [carlosdoki/MovieZtream#6]
![image](https://user-images.githubusercontent.com/37035465/84438727-b2befe80-ac3f-11ea-8cee-aa478303ac6e.png)

**_And the Start Error::_**

root@mzsite:/home/krehan/Downloads/MovieZtream# ./start-mz.sh 

Starting the MySQL database container...

db

Starting the AppDynamics db agent container...

db-agent

Starting the MovieZtream ratings container...

rt

Starting the MovieZtream service container...

sv

Starting the MovieZtream UI container...

Error response from daemon: driver failed programming external connectivity on endpoint ui (92972eaaa50d74222a2e4a630d0281f3a18fc99595faf6835d5471a5a6bcca14): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
Error: failed to start containers: ui

Starting the JMeter load container...

Error response from daemon: Cannot link to a non running container: /ui AS /mz-load/ui
Error: failed to start containers: mz-load

Waiting for agent registration...

Starting AppDynamics machine agents on MovieZtream containers...

OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
Error response from daemon: Container 8fea13f92e2dddb6e0f8f401be2b3ca6fcf2521fd4adea7ff3181591b2effb60 is not running

All containers started! You can access the AppDynamics Controller at :8090

**Comment by khalidrehan** [comment]
On the Controller:
![image](https://user-images.githubusercontent.com/37035465/84439034-295bfc00-ac40-11ea-83ce-97eae00ad748.png)

Only one Tier with one Node:
![image](https://user-images.githubusercontent.com/37035465/84439061-34af2780-ac40-11ea-8da3-096f764764c1.png)

**Comment by carlosdoki** [comment]
I'm correct this
