### ISSUE TITLE
Java Agent Update to 20.3.0+

### ISSUE THREAD

**Issue by khalidrehan** [carlosdoki/MovieZtream#7]
Hi Carlos,

The app is working great.

Can you tell me how to update the Java Agent?
It is ver 4.5.18.xxx and I need it to be ver 20.3.0+

Thanks in advance,
Khalid.

**Comment by khalidrehan** [comment]
And really thanks for your great support 👍

**Comment by carlosdoki** [comment]
Correct the scripts to work with new version of agents #10
